shm_size: '128G'
batch_size_per_gpu: 1
export_format: 'seg-coco:raw'
epochs: 100
MAX_SIZE_TRAIN: 1333
MAX_SIZE_TEST: 1333
MIN_SIZE_TEST: 800
MIN_SIZE_TRAIN: 800

CHECKPOINT_PERIOD: 100

BASE_LR: 0.0001
